CC = g++
FLAGS = -lm
exemplo1: exemplo1.cpp matriz1.dat
	$(CC) -o exemplo1 exemplo1.cpp $(FLAGS) && ./exemplo1 matriz1.dat

exemplo2: exemplo2.cpp matriz2.dat
	$(CC) -o exemplo2 exemplo2.cpp $(FLAGS) && ./exemplo2 matriz2.dat	

clean: 
	rm -r exemplo1 exemplo2